  name: Egg iOS CI

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  build:
    name: Build Archive Export App And Notify Dingtalk
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get IPA Path
        run: |
           echo "------------------------------------------"
           echo "The IPA file message: ${{ steps.export_ipa.outputs.export_ipa_msg }}"
           echo "The IPA file is located at: build/${{ github.event.repository.name }}-${{ github.sha }}.ipa"
    
          
     
